### ISSUE TITLE
Fix type piracy

### ISSUE THREAD

**Issue by tkelman** [JuliaDiffEq/RecursiveArrayTools.jl#3]
tracking issue for https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/commit/f976781e55a55b1ec977e1d8e489771d8adad288#commitcomment-21917646

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/commit/33b2a7a4167fc53492cb050ed52c37572054ac66
