### ISSUE TITLE
Change in result of vec(sol) in 0.7 as compared to 0.6.

### ISSUE THREAD

**Issue by Vaibhavdixit02** [JuliaDiffEq/RecursiveArrayTools.jl#38]
The way `vec ` is dealing with `ODESolution` seems to have changed. 
```
f1 = @ode_def LotkaVolterraTest begin
  dx = a*x - x*y
  dy = -3y + x*y
end a
u0 = [1.0;1.0]
tspan = (0.0,10.0)
p = [1.5]
prob1 = ODEProblem(f1,u0,tspan,[1.5])
t = collect(range(0, stop=10, length=200))
sol = solve(prob1,Tsit5();saveat=t,save_everystep=false,dense=false,kwargs...)
vec(sol)
```
Gives an array of length 200 and does not unwrap the 2-element arrays as it should (and gave in 0.6).

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/commit/2313800b0c922b758c3a0f87108c64a2c9512f3c
