### ISSUE TITLE
Reshape

### ISSUE THREAD

**Issue by mcabbott** [JuliaDiffEq/RecursiveArrayTools.jl#47]
I get an error reshaping these lazy arrays, because their `length` means something else. Is there a reason not to fix this, perhaps like this? 
```
using RecursiveArrayTools

A = VectorOfArray([rand(4) for i=1:3] )
size(A) == (4,3)

reshape(A, (2,6))  # error

function Base._reshape(parent::VectorOfArray, dims::Base.Dims)
    n = prod(size(parent))
    prod(dims) == n || _throw_dmrs(n, "size", dims)
    Base.__reshape((parent, IndexStyle(parent)), dims)
end

reshape(A, (2,6)) # no error! 
```

**Comment by ChrisRackauckas** [comment]
It seems to work well so I just dropped it right in: https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/commit/63adb2a6f66fa9e24fd1655ff89c353195ce3f0f Thanks for the suggestion and the code!

**Comment by mcabbott** [comment]
Thanks, that was quick!
