### ISSUE TITLE
setindex not implemented

### ISSUE THREAD

**Issue by daviehh** [JuliaDiffEq/RecursiveArrayTools.jl#51]
Right now, one may read from the partition via `.x[...]`, but not write:

```
using RecursiveArrayTools
u0=ArrayPartition(rand(2,2),rand(3,3),rand(4,4))
u0.x[1]=rand(2,2)
```

> ERROR: MethodError: no method matching setindex!(::Tuple{Array{Float64,2},Array{Float64,2},Array{Float64,2}}, ::Array{Float64,2}, ::Int64)

For in-place updates `f(du, u,p,t)`, it would be useful to be able to do the the assignment to du via the `.x[...]` index rather than the normal linear index.

**Comment by daviehh** [comment]
Sorry, just found out broadcasting `u0.x[1] .= rand(2,2)` works as intended. Maybe add this to documentation?

**Comment by YingboMa** [comment]
`u0.x` is a tuple, so you can only mutate `u0.x[1]` by in-place operations.

**Comment by daviehh** [comment]
@YingboMa got it, thanks!
